name: iris
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python iris.py

          # Write your CML report
          echo "## MODEL METRICS" > report.md
          cat metrics.txt >> report.md
          
          echo "## Data Visuals" >> report.md
          cml-publish feature_importance.png --md >> report.md 
          
          cml-send-comment report.md
